apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: members.williamnoble.developer.com
spec:
  group: williamnoble.developer.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
  scope: Namespaced
  names:
    kind: Member
    singular: member
    plural: members
    shortNames:
      - mbrs
